export const INSTRUMENTS = [
  {
    id: 'piano',
    name: 'Piano',
    icon: '🎹',
    harmonics: [
      { ratio: 1, gain: 1.0, decay: 2.0 },
      { ratio: 2, gain: 0.5, decay: 1.5 },
      { ratio: 3, gain: 0.25, decay: 1.0 },
      { ratio: 4, gain: 0.15, decay: 0.8 },
      { ratio: 5, gain: 0.08, decay: 0.6 },
      { ratio: 6, gain: 0.04, decay: 0.5 },
      { ratio: 7, gain: 0.02, decay: 0.4 },
    ],
    hammerNoise: true,
    attackTime: 0.005,
    masterGain: 0.35,
    filterMult: 12,
  },
  {
    id: 'epiano',
    name: 'Electric Piano',
    icon: '🎸',
    harmonics: [
      { ratio: 1, gain: 1.0, decay: 2.5 },
      { ratio: 2, gain: 0.6, decay: 2.0 },
      { ratio: 3, gain: 0.15, decay: 1.2 },
      { ratio: 4, gain: 0.05, decay: 0.8 },
      { ratio: 7, gain: 0.03, decay: 0.5 },
    ],
    hammerNoise: false,
    attackTime: 0.002,
    masterGain: 0.3,
    filterMult: 8,
    vibratoRate: 5,
    vibratoDepth: 3,
  },
  {
    id: 'organ',
    name: 'Organ',
    icon: '🎵',
    harmonics: [
      { ratio: 0.5, gain: 0.5, decay: 10 },
      { ratio: 1, gain: 1.0, decay: 10 },
      { ratio: 2, gain: 0.8, decay: 10 },
      { ratio: 3, gain: 0.6, decay: 10 },
      { ratio: 4, gain: 0.4, decay: 10 },
      { ratio: 6, gain: 0.2, decay: 10 },
      { ratio: 8, gain: 0.1, decay: 10 },
    ],
    hammerNoise: false,
    attackTime: 0.01,
    masterGain: 0.2,
    filterMult: 10,
    sustained: true,
  },
  {
    id: 'synthpad',
    name: 'Synth Lead',
    icon: '🎛️',
    harmonics: [
      { ratio: 1, gain: 1.0, decay: 3.0 },
      { ratio: 2, gain: 0.7, decay: 2.5 },
      { ratio: 3, gain: 0.5, decay: 2.0 },
      { ratio: 4, gain: 0.3, decay: 1.5 },
    ],
    oscType: 'sawtooth',
    hammerNoise: false,
    attackTime: 0.01,
    masterGain: 0.15,
    filterMult: 6,
  },
  {
    id: 'strings',
    name: 'Strings',
    icon: '🎻',
    harmonics: [
      { ratio: 1, gain: 1.0, decay: 4.0 },
      { ratio: 2, gain: 0.6, decay: 3.5 },
      { ratio: 3, gain: 0.3, decay: 3.0 },
      { ratio: 4, gain: 0.15, decay: 2.5 },
      { ratio: 5, gain: 0.08, decay: 2.0 },
    ],
    hammerNoise: false,
    attackTime: 0.15,
    masterGain: 0.25,
    filterMult: 8,
  },
  {
    id: 'harmonium',
    name: 'Harmonium',
    icon: '🪗',
    // Sample-based instrument — no harmonics (handled by useHarmoniumAudio)
    sampleBased: true,
  },
]

export const DEFAULT_INSTRUMENT = 'piano'
